### PR TITLE
Implement GPS location, and bearing acquisition and export.

### PR DESCRIPTION
**Pull request by skinkie**
Three years and 10 days after the suggestion https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/152#issuecomment-406803520
and being inspired by @mores, a fix for #152

**What does this implement/fix? Please describe.**
Export longitude,latitude,accuracy,bearing,bearingaccuracy along with the WiFiDetails.

**Does this close any currently open issues?**
#152 

**Additional context**
This feature would be really useful if the app would support continuous exports, or write something to a file.

I am really a _novice_ programmer in the Kotlin language. It might be worthwhile to move the location activity to the MainContext, to make the variable private (again).

**Where has this been tested?**
- Operating System: Linux
- Platform: Android 10
- Target Platform:
- Toolchain Version:
- SDK Version:

### CODE REVIEW

**Comment by skinkie** [comment]
@VREMSoftwareDevelopment any reason to close this issue without any feedback?

**Comment by VREMSoftwareDevelopment** [comment]
@skinkie there were not response to the PR feedback provided by us for over 1/2 year.
Which stand to show that there no interest fixing the issues in the PR.
It is always possible to re-open existing PR or submit a new PR with new code changes.

**Comment by skinkie** [comment]
A non-project member is not able to open a closed pull request. So yes, an open source product could be forked, but still it does not make sense when a feature is provided no reply at all is provided.

**Comment by VREMSoftwareDevelopment** [comment]
We have re-opened the PR, please response to our feedback(s) that was provided 1/2 year ago

**Review by VREMSoftwareDevelopment — CHANGES_REQUESTED** [review]

**Comment by VREMSoftwareDevelopment** [comment]
Please make sure that this PR solves concerns raised in PR #286, since they are related.

Thanks

**Comment by skinkie** [comment]
Thanks. Very strange I have not received a notification about this. I'll see if I can make it work with the provided feedback.

**Comment by VREMSoftwareDevelopment** [comment]
Here a few links to reference documentation that may help:
[Optimize location for battery](https://developer.android.com/guide/topics/location/battery)
[Background Location Limits](https://developer.android.com/about/versions/oreo/background-location-limits)

**Pull request closed without merging**
