### PR TITLE
Add Hebrew translation

### PR DESCRIPTION
**Pull request by GreenLunar**

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Thanks for the translation.

Can we add you as contributor to the project in the Application About page?
If yes, can you please email your full name.

Thanks.

**Comment by GreenLunar** [comment]
This is not my real name, but this is the account that I use to contribute translations with: "Genghis Khan" <genghiskhan@gmx.ca>; you can just write "Genghis" or not mention anything.

**Comment by VREMSoftwareDevelopment** [comment]
[Hebrew translations are under HE and IW] (https://developer.android.com/reference/java/util/Locale.html)

**Comment by GreenLunar** [comment]
Yes.  I recommend adding a symbolic link.  See F-Droid and JAWS https://github.com/jannispinter/jaws/tree/master/app/src/main/res

**Pull request merged**
