### PR TITLE
SystemTheme TextColor correction

### PR DESCRIPTION
**Pull request by Leptopoda**
**What does this implement/fix? Please describe.**
- fixing the color issue when the system theme is in "light/day" mode
-I temporally removed the light theme

**Does this close any currently open issues?**
- not marked as one

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Please note that `Theme.AppCompat.Light` is not `Theme.AppCompat.DayNight`.

Please take a look at [Support Lib 23.2.0 blog post](https://android-developers.googleblog.com/2016/02/android-support-library-232.html) AppCompat DayNight theme  section.

**Comment by Leptopoda** [comment]
Off cause ``DayNight`` isn't the same as ``Light`` but the most ROM's (except lineage and some others) use the day theme as their default. So the app will display the ``Light/Day`` theme when the ``SystemTheme`` is chosen. Those ROM's giving the ability to change the mode to ``Night`` will display dark. (those roms provide the ability to make the theme light system wide). Of cause with the removal of the ``LightTheme`` you lose the ability to force the app to light when the OS is Dark. But who doesn't want system integration?

P.S. I just started to recode the whole theme mechanism. I plan to just use ``AppCompatDelegate`` to switch themes and thus only one theme is needed. I just don't have time jet.

**Comment by Leptopoda** [comment]
If you wan't I can reimplement the ``LightTheme`` so you can force the theme to light and just have to merge the ThemeCorrection where the Action bar and its Text color where to similar.

**Comment by VREMSoftwareDevelopment** [comment]
To merge this pull request in the current state, please put light theme back in. Otherwise we will wait until you have implement new theme mechanism.

**Comment by Leptopoda** [comment]
shure! thats why I firstly just uncommented it. (even when I can't see the reason why"

**Pull request merged**
