### PR TITLE
[Work in Progress] Allow language to be changed in Settings

### PR DESCRIPTION
**Pull request by rupran**
This is an attempt to fix the second part of issue #124.

This change adds another option in the SettingActivity which allows
the user to select a language. Currently, this is only a proof of
concept and is only implemented for German and English, as I didn't
find a way to automatically determine all available translations yet
(i.e. all languages for which values-XX exists) - if anyone knows
how to do that in a generic way, please let me know and I'll
implement this.

Also, if there's a nicer way to do this, let me know, this is my
first attempt at playing around with Android apps.

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Thanks, excellent start.

Please take a look at the following:
- [CountryPreference.java](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/main/java/com/vrem/wifianalyzer/settings/CountryPreference.java)
- [Country.java](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/main/java/com/vrem/wifianalyzer/wifi/band/Country.java)

By doing something similar to the Language selector, will allow Android OS to supply language descriptions in the selected language,  which will remove requirement to maintain language descriptions in the `strings**.xml` or `arrays**.xml` files.

**Comment by rupran** [comment]
Thanks for the pointers, I will look into the mechanisms there and try to use them for the languages.

The failing checks in Travis seem to mainly have to do with an issue in robolectric itself (see https://github.com/robolectric/robolectric/issues/2909). Should I add ` @config{sdk = N}` to the failing ones as the last comment on this issue suggests?

**Comment by VREMSoftwareDevelopment** [comment]
There are two type of tests in the application:
1. junit tests using plain Java (fast and easy to write), examples:
    - [CountryTest.java](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/test/java/com/vrem/wifianalyzer/wifi/band/CountryTest.java)
    - [MainReloadTest.java](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/test/java/com/vrem/wifianalyzer/MainReloadTest.java) using Mockito (some other test may use Powermock)
2. junit tests for java classes that use/access Android API require [robolectric](http://robolectric.org/c (slower and harder to write), example:
    - [StartMenuPreferenceTest.java](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/master/app/src/test/java/com/vrem/wifianalyzer/settings/StartMenuPreferenceTest.java)

Changing tests from one type to another will require changing the required annotation and setup inside the test. 
The goal is to write more (1.) tests, unless the test will require robolectric.
Hope this helps

**Comment by rupran** [comment]
I've reworked the Language selection to pull its values from the `LocaleType` enum.

Languages are displayed with their full name (i.e. "English (United States)"), as the two variants of Chinese would not be distinguishable otherwise.

One minor thing which I don't know how to fix yet is that if the phone language is set to something other then the implemented translations (say, Danish - DK), the "Language" list will have no default value - I haven't found a simple way to look up the currently used localization (`Locale.getDefault()` contains the phone language (DK) in this case, not the one in use by the app (which would be EN as the default fallback)).

Additionally, there is currently no way to switch back to the "unimplemented" translation once a user has selected a language from the menu.

**Comment by rupran** [comment]
The problems above are fixed now, the `LocaleType` Enum now contains an entry for `Locale.getDefault()`. In order to not display this entry twice if a translated Locale is the default Locale, `LanguagePreference.getData()` builds a set over the country codes.

**Comment by Korb** [comment]
I suggest you consider changing the language of the WiFiAnalyzer through a single control center for the languages of installed applications, available in the latest versions of Google Android. Read more about it in the article "[Change app language on your Android phone](https://support.google.com/android/answer/12395118)" of the official OS help. [Screenshot](https://drive.google.com/file/d/1rhT3cFpo8cpeLrXIPteFH-0202ks_IYy/view)

**Pull request merged**
