### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by Findus23**
Hello,

I wasn't able to translate three strings:
- _channel_rating_best_alternative_ and _channel_rating_best_none_:
    - Where can I find them in the app?
- action_vendors
    - What do you mean by "Vendors"? The app doesn't display any data for me.

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Thanks for the translation.

Here are screenshots that may help with translations.
- channel_rating_best_alternative and channel_rating_best_none (text in red): [Channel Rating](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/raw/master/screenshots/screenshot7.png)
- action_vendors: [Vendor MAC Address List](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/raw/master/screenshots/screenshot8.png)

Can we add you as contributor to the project in the Application About page?
If yes, can you please email your full name.

Thanks.

**Comment by Findus23** [comment]
Thanks for the quick response.
It is still not clear to me, what the Vendor-Tab does.

My full name is "Lukas Winkler".

**Comment by VREMSoftwareDevelopment** [comment]
Say, Access Point Mac Address is 1C:DE:A7:01:BA:CF.
We map MAC Address to actual vendor/manufacture, in this case it is CISCO.
Vendors-Tab is just a list of all Access Point MAC Addresses ranges map to specific vendor or manufacture of the device.

**Comment by Findus23** [comment]
Thanks, now it is clear to me.

**Pull request merged**
