### PR TITLE
Adds Latitude Longitude in Exports - Issue 152

### PR DESCRIPTION
**Pull request by mores**
**What does this implement/fix? Please describe.**
Export now contains latitude and longitude.

**Does this close any currently open issues?**
No. Issue 152 has already been closed as wontfix

**Where has this been tested?**
- Operating System: Android 8.1.0
- Platform: Pixel C
- Target Platform: ( built using gradlew )
- Toolchain Version: ( built using gradlew )
- SDK Version: ( built using gradlew )

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
@mores 
Thank you for pull request.

Hera are a few questions:
- Location information is only use in Export, but application is asking it in Main Activity every second. Some how it does not make sense. Is there a better way of doing it?
- How pulling GPS from the phone every second effects the battery life? It is know that it is expensive battery operation.
- Have you considered [Wi-Fi location: ranging with RTT](https://developer.android.com/guide/topics/connectivity/wifi-rtt)? Will this be a better solution?

**Comment by mores** [comment]
> * Location information is only use in Export, but application is asking it in Main Activity every second. Some how it does not make sense. Is there a better way of doing it?

GPS location is not instantaneous. Main is caching the latest location, then export is occurring instantaneously. Not sure if there is a better way.

> * How pulling GPS from the phone every second effects the battery life? It is know that it is expensive battery operation.

True, the quicker the updates, the quicker the battery will drain. Perhaps a user setting could be added to indicate how often to refresh GPS location.

> * Have you considered [Wi-Fi location: ranging with RTT](https://developer.android.com/guide/topics/connectivity/wifi-rtt)? Will this be a better solution?
That may be a better solution, I will have to investigate that.

**Comment by mores** [comment]
What I would really like to see as a feature:
1. Turn record on
2. As you walk around signal strength and location are recorded.
3. Turn record off
4. Export that entire data set so a png image can be created to show coverage.

**Comment by VREMSoftwareDevelopment** [comment]
All these new features sounds great. 
Will be waiting for the new PR.

**Pull request closed without merging**
