### PR TITLE
#23, Added Location permission and runtime requests

### PR DESCRIPTION
**Pull request by harsu-ag**
Added COARSE_LOCATION permission to manifest, and also added required runtime requests in `AccessPointsFragment` 

Apart from that there has also been an upgrade to gradle file to support latest Android versions(25)

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
General Issues:
1. Travis CI build failed [https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/186863961](https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/186863961)
2. Codacy reports code quality issues [https://www.codacy.com/app/vremsoftwaredevelopment/WifiAnalyzer/pullRequest?prid=462033](https://www.codacy.com/app/vremsoftwaredevelopment/WifiAnalyzer/pullRequest?prid=462033)

**Comment by VREMSoftwareDevelopment** [comment]
99% of the users do not need the location permission in the application and do not want to see this new permission required to use the application. We would like not to change the existing code base and application. Our preference is to create a new app in the Play Store to accommodate 1% of the user base that requires the location permission in the application.  Two different code branches may be needed to accomplish this. 

Do you have any other ideas how to implement this?

Thanks,

VREM Development Team.

**Comment by harsu-ag** [comment]
Sorry, but I have not much idea of how to do this. 
Thanks.

**Comment by Aiden01** [comment]
You can have more apks in production, on the google play developer console.
You can release 2 apk, the first one like it's now, and the second with the new ACCESS_COARSE_LOCATION permission that will be distributed only to the users that really need it (so you will need to know what devices are "affected").
Following this way, you don't need to make another app.

**Pull request closed without merging**
