### PR TITLE
Added timestamp to exported Access_Point filename

### PR DESCRIPTION
**Pull request by chankruze**
**What does this implement/fix? Please describe.**
- It implements current date & time stamp to generated Access_Point file name.

**Does this close any currently open issues?**
- No

**Where has this been tested?**
- Operating System: Android
- Platform: Android 9 (API level 28)
- Target Platform: Android 9.0 (Qualcomm MSM8953 Snapdragon 625)
- Toolchain Version: android-ndk-r19c
- SDK Version: 28

### CODE REVIEW

**Comment by chankruze** [comment]
I don't know what's wrong with TRAVIS CI, it never passes anything. Always fail. I can't understand how people are using it.

The app compiled successfully, generated both debug and signed apk successfully, installed and running perfect on both emulator and physical device. Added 5 lines and travis is failing, i will never contribute to projects who have travis-ci.

**screenshots**

Screenshot_20190401-201524
Screenshot_20190401-201551
Screenshot_20190401-201559

**Comment by VREMSoftwareDevelopment** [comment]
@chankruze 

### Continuous Integration (CI):
"CI was intended to be used in combination with automated unit tests written through the practices of test-driven development. Initially this was conceived of as running and passing all unit tests in the developer's local environment before committing to the mainline. This helps avoid one developer's work-in-progress breaking another developer's copy." Reference: [Wikipedia Continuous integration](https://en.wikipedia.org/wiki/Continuous_integration)

### Test-driven development (TDD):
"Test-driven development is a software development process that relies on the repetition of a very short development cycle: requirements are turned into very specific test cases, then the software is improved to pass the new tests, only. This is opposed to software development that allows software to be added that is not proven to meet requirements." Reference: [Wikipedia Test-driven development](https://en.wikipedia.org/wiki/Test-driven_development):

### The Travis CI build failed

[This link](https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/514178099?utm_source=github_status&utm_medium=notification) or below from Travis CI

FailedBuild

### How to run application tests
[Running unit tests and jacoco coverage report](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#running-unit-tests-and-jacoco-coverage-report)


Regards,

VREM Development team

**Comment by chankruze** [comment]
@VREMSoftwareDevelopment 
I am debugging to find out why `Task 'jacocoTestDebugUnitTestReport' not found in root project`
hope i can figure out the reason.

**Comment by chankruze** [comment]
Ok i fixed the issue, it was due to some build environment stuff.
Will open a new PR.

**Comment by chankruze** [comment]
I was wrong man !
I build on master branch so it worked.
But feature branch has conflicts.
`The option setting 'android.enableUnitTestBinaryResources=true' is experimental and unsupported.`

**Comment by VREMSoftwareDevelopment** [comment]
### How to run application tests

Running unit tests and jacoco coverage report

Master Branch:
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer#running-unit-tests-and-jacoco-coverage-report

Feature Branch:
https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/tree/feature#running-unit-tests-and-jacoco-coverage-report

**Pull request closed without merging**
