### PR TITLE
make it more clear that SSID filter is case sensitive

### LINKED ISSUE #441: make it clear that SSID filter is case sensitive
**Is your feature request related to a problem? Please describe.**
When I entered an SSID filter, it was not immediately clear this was case sensitive. 
For example, I am connected to "AndroidWifi" and want to filter on it. I type in the filter "andro". Nice, I only see the AndroidWifi network. Now, I go to the timechart tab: nothing comes here. 
The confusion comes from the fact that in the Access Point tab, I only see the network I filtered on, but not because of the filter, but because I assume the connected network is always shown on top (I only realized this later). 
So: the combination of the fact that it was not clear to me that connected network is always shown in AP tab and ssid filter is case sensitive, I ended up losing a lot of time 😅 

**Describe the solution you'd like**
The easiest solution is just place some extra info next to the SSID field in the filter dialog that indicates this field is case sensitive. For example:
image
What would also help, is make it somehow more obvious that the network on top in the AP tab list is the connected network, regardless of any filters that have been set. Although, it's basically another issue. 

**How I can help**
I can make a PR to change the SSID field title.

### PR DESCRIPTION
**Pull request by mx1up**
**What does this implement/fix? Please describe.**
- adds "(case sensitive)" to the SSID filter title

**Does this close any currently open issues?**
fixes #441

**Additional context**
- I guess this string might need translation now (currently it is marked as untranslatable), if so, please explain how your translation workflow works. 

**Where has this been tested?**
- Tested in emulator

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
This would definitely require translation to other languages currently supported by the application.
There is no automatic translation workflow available in this project, if you know of any automatic translation you are welcome to implement it.

The other choice could be implementation of the universal icons (no translation required), ie:
gui-case-sensitive-svgrepo-com

**Comment by mx1up** [comment]
ok, I will just update the translation files. For the languages that I do not know, should I provide an English stub in each language file or do I leave it out so there is fall back on the language agnostic `strings.xml`? 
Or maybe I can use google translate as it is a quite short translation? (though maybe not easy for google translate to interpret correctly..)

As a translation workflow, Transifex comes to mind, which is free for open source projects. However, I don't have experience implementing it and as this project is as good as finished, the return on investment seems quite low.

**Comment by VREMSoftwareDevelopment** [comment]
> Or maybe I can use google translate as it is a quite short translation? (though maybe not easy for google translate to interpret correctly..)

Probably Google Translate is good enough for now.

**Comment by mx1up** [comment]
I have added translation, based on google translate and wikipedia. I also verified that longer strings don't pose a problem.

Is it okay to rebase?

**Comment by VREMSoftwareDevelopment** [comment]
Since there are not conflicts, rebase is not necessary.

**Comment by mx1up** [comment]
Okay, so I guess I'm ready then..

**Comment by VREMSoftwareDevelopment** [comment]
Thank you for your contribution

**Comment by mx1up** [comment]
thanks for accepting 👍

**Comment by Mangager** [comment]
My personality idea

**Comment by Mangager** [comment]
Places talking and wireless and that's

**Pull request merged**
