### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Tobaloidee**
Hi Sir, I have replaced all the .png images with the new icons. I hope i did it right. :)  Thanks!

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Please add "svg" files to images folder.

**Comment by VREMSoftwareDevelopment** [comment]
@Tobaloidee 

### We are having a few issues with the svg files that were provided:
1) Android Studio IDE is not playing nice with the files, here is a screenshot example:
configureimageasset
2) Also we would like to make shadow color closer to the background color.
Here are possible color choices: background = #308234, shadow = #2E7D32
3) SVG files have different viewBox and px sizes (such as 1000, 108, etc). Is its possible to make them consistent in all the files (such as: viewbox 192 and size 192x192px)?
4) SVG contain a lot of path that are not used, It creates issues when converting SVG to Android Vector format.

### We have added some example svg files to the repository:
- [background](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/images/svg/background.svg)
- [foreground](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/images/svg/foreground.svg)
- [icon](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/blob/feature/images/svg/icon.svg)

**Comment by VREMSoftwareDevelopment** [comment]
Thanks.

**Comment by Tobaloidee** [comment]
just let me know Sir if there's still issues and I will edit

**Comment by VREMSoftwareDevelopment** [comment]
All the (svg and png) images are updated and are in the feature branch.
You are welcome to review them and see if everything looks good.

**Pull request merged**
