### PR TITLE
System Theme option reworked

### PR DESCRIPTION
**Pull request by Leptopoda**
What does this implement/fix? Please describe.

I reworked my last commit other is the same:
  Implements a new Theme called "system". The systemTheme is being controlled by the system and displays either a dark or light theme. This feature implements well with android's like LineageOS. Here is the system wide theme!!

Does this close any currently open issues?
-No

Additional context

    Future additions are applying the system accentColor to the app.
    Future code cleanup with "AppCompatDelegate.MODE_NIGHT_..." FOLLOW_SYSTEM / NO / YES" so the existing styles can be removed and controlled by forcing the themeMode thus only one style is needed.

Where has this been tested?

    Operating System: Lineage OS 15.1 (Android 8.1), Android Preview SDK 28, Android 7.1.1, Android 8.0 (and of cause the emulator in this case android P again)
    Platform: -
    Target Platform: -
    Toolchain Version: -
    SDK Version: 27, 28, 25,26

### CODE REVIEW

**Comment by Leptopoda** [comment]
Why isn't it passing the check?
it says it has problems with the gradle but i didn't change anything there?
what can I do?

**Comment by VREMSoftwareDevelopment** [comment]
Please take a look at the log file produced by [Travis-CI](https://travis-ci.org/VREMSoftwareDevelopment/WiFiAnalyzer/builds/391319943?utm_source=github_status&utm_medium=notification), specifically lines: 2036 to 2040.

**Comment by Leptopoda** [comment]
How should I handle the languages should I just upload it with the English words in it?

**Comment by VREMSoftwareDevelopment** [comment]
Translate what you can, and add the rest in English. Looks like you have done exactly that.

**Pull request merged**
