### PR TITLE
Trad Chinese (for taiwan)

### PR DESCRIPTION
**Pull request by pupu2314**

### CODE REVIEW

**Comment by VREMSoftwareDevelopment** [comment]
Can you please fix the error in the build, in order for us to merge your pull request?

Thank you

VREM Software Development Team

**Comment by VREMSoftwareDevelopment** [comment]
- There is no need to translate values that have attribute `translatable="false"`
- Please try the following name `values-zh-rTW` (not `values-zhtw`) for the resource folder. This may fix the build error.

```
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /home/travis/build/VREMSoftwareDevelopment/WiFiAnalyzer/app/src/main/res/values-zhtw: Error: Invalid resource directory name
```

Regards,

VREM

**Comment by pupu2314** [comment]
Thanks

**Comment by VREMSoftwareDevelopment** [comment]
Can we add you as contributor to the project in the Application About page?
If yes, should we use your GitHub name (TaiXiong)?

Thanks.

**Comment by VREMSoftwareDevelopment** [comment]
Can you also add translation to the following?

` <string name="ap_view_title">Access Point Display</string>`

Thanks

**Comment by pupu2314** [comment]
<string name="ap_view_title">顯示AP</string>

**Pull request merged**
